language: node_js
cache:
  directories:
  - node_modules
after_failure:
  - ./test/functional/scripts/upload-artifacts.sh /home/travis/build/dadi/publish/test/functional/output
after_success:
  - ./test/functional/scripts/upload-artifacts.sh /home/travis/build/dadi/publish/test/functional/output
notifications:
  email: false
  slack:
    on_failure: always
    on_success: never
    rooms:
      secure: MCz3nE/G7lBVfd6GFCzC9rsbx5UwviAyq1S2cz485YOrn1l44GyHXhzpZywSYVtMNwUUBa5nIatZf/VETxLfbneQ3rm/DmaPxUhxNyDfICg8cytWNbF+yOXpcc+Y14HunUJ1K2DNRUech86Zqc/ndV0uuz+hmMZye3jAwMzFw58TPI0LjRB9uwyY1Yq2w3MIGm2Ns5neZM/PyEyJURMApSvOU7yeMcEIhXskezmuua4qKorFQsZx6+m9Ylgicf3k7X2VHcsArwLjGxDzx8AoGrQ1DTL4Mv+ogjn1+/oapZ6wtxH3TiiUGlkBZKa+owhnDNmLlY8hah6XH0S8K8oY0uNDQlQ19xsdBmYSqu9PBTye8cT7dTJABPtMOs/ByYyIVnI4q2V+B5a9kfT1FcRD7VnVnbdg0chxwiZG+DmjJ5U2efMqeDO9JT7G6834dqBiG7njurJAStEVfjvYLVxhWmuYWpAytEoadRn2S4Er8GboJoiA1LaDJCKXaTxtYeMYeGdL0rzWFyFBnXgX5IOR6rkeG4gT77xQPycz0clZEZOeQy7S3tB/RmkaIg3VkxSEET5xAKBhJYEdsK7SpTEEm60AE4CRWlmrmbkWOA8qTXGd5p3/DKJ+rKj0+V9cmEssnUC49/uLU6/SO/u1QHZcH2vduJTAHIEFFmgpljrIRlk=
node_js:
- '8'
